{{- if .Values.serviceMonitor.enabled }}
{{/* Requires the Prometheus Operator CRDs.
     Name: Hemang | 24bcs10209 */}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stacks.fullname" . }}
  labels: {{- include "stacks.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "stacks.backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
