# Session 20 mini project - Name: Hemang | Enrollment number: 24bcs10209
apiVersion: v1
kind: Service
metadata:
  name: session20-mini
  namespace: session20
  labels: { app: session20-mini }
spec:
  type: ClusterIP
  selector: { app: session20-mini }
  ports:
    - port: 80
      targetPort: 80
