{{/* Name: Hemang | 24bcs10209 */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-chart.fullname" . }}
  labels: {{- include "notes-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "notes-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "notes-chart.selectorLabels" . | nindent 8 }}
      annotations:
        # roll the pods whenever the ConfigMap content changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: notes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 80, name: http }]
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: page
              mountPath: /usr/share/nginx/html
      volumes:
        - name: page
          configMap:
            name: {{ include "notes-chart.fullname" . }}
