#!/bin/bash
# ---------------------------------------------------------------------------
# sysinfo.sh - System Information Script
#
# Name             : Hemang
# Enrollment number: 24bcs10209
#
# Prints a summary of the machine it runs on, asks the user where to save a
# report, and writes the full running-process list to that file using output
# redirection.
#
# Covers: variables, date, hostname, whoami, df, ps, read -p, mkdir, touch, >
# ---------------------------------------------------------------------------

# ---- variables: capture command output with $( ) ---------------------------
today=$(date)
box=$(hostname)
me=$(whoami)
kernel=$(uname -s)
disk_summary=$(df -h / | awk 'NR==2 { print $3 " used of " $2 " (" $5 " full)" }')
proc_count=$(ps ax | wc -l | tr -d ' ')

# ---- 1. print the basics ---------------------------------------------------
echo "==============================================="
echo "            SYSTEM INFORMATION REPORT           "
echo "==============================================="
echo "Date          : $today"
echo "Hostname      : $box"
echo "Username      : $me"
echo "Kernel        : $kernel"
echo "Root disk     : $disk_summary"
echo "Processes     : $proc_count currently running"
echo

# ---- 2. disk usage ---------------------------------------------------------
echo "----------- DISK USAGE (df -h) ----------------"
df -h
echo

# ---- 3. running processes --------------------------------------------------
echo "----------- TOP 10 PROCESSES BY CPU -----------"
ps aux | head -1
ps aux | tail -n +2 | sort -rk 3 | head -10 | cut -c1-100
echo

# ---- 4. take input from the user with read -p ------------------------------
read -p "Directory to save the report in : " report_dir
read -p "Report file name               : " report_file

# fall back to defaults if the user just pressed Enter
report_dir=${report_dir:-./reports}
report_file=${report_file:-processes.txt}
report_path="$report_dir/$report_file"

# ---- 5. create the directory and the file ----------------------------------
mkdir -p "$report_dir"
touch "$report_path"

# ---- 6. store the process list in the file with > redirection --------------
{
    echo "Process report generated by sysinfo.sh"
    echo "Name   : Hemang"
    echo "Roll   : 24bcs10209"
    echo "Host   : $box"
    echo "User   : $me"
    echo "Date   : $today"
    echo "-----------------------------------------------"
} > "$report_path"

ps aux >> "$report_path"

# ---- 7. confirm ------------------------------------------------------------
lines=$(wc -l < "$report_path" | tr -d ' ')
echo
echo "Created directory : $report_dir"
echo "Created file      : $report_path"
echo "Wrote $lines lines of process data to $report_path"
echo
echo "----------- FIRST 12 LINES OF THE SAVED REPORT ----"
head -12 "$report_path" | cut -c1-100
