{
 "title": "TaskBoard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(taskboard_http_requests_total[5m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Tasks stored",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "max(taskboard_tasks_total)" }
   ]
  },
  {
   "title": "Backend pods UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=\"taskboard-pods\"})"
    }
   ]
  },
  {
   "title": "Errors (5xx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(taskboard_http_errors_total)"
    }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(taskboard_http_requests_total[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average request latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pod) (taskboard_request_latency_seconds)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}